<?php

namespace app\modules\adminxx\controllers;

use Yii;
use app\modules\adminxx\models\UControl;
use yii\web\Controller;

/**
 * Class MainController
 * @package app\modules\adminxx\controllers
 */
class MainController extends Controller
{
    /**
     * @var string
     */
    public $layout = '@app/modules/adminxx/views/layouts/adminxxLayout.php';

    /**
     * Ответ, который будет возвращаться на AJAX-запросы
     * @var array
     */
    public $result = [
        'status' => false,
        'data' => 'Інформацію не знайдено'
    ];

    /**
     * @var null
     */
    private $_configs = null;

    /**
     * @param $action
     * @return bool
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        $tmp = Yii::$app->language = Yii::$app->userProfile->language;

        if (defined('YII_DEBUG') && YII_DEBUG) {
            Yii::$app->getAssetManager()->forceCopy = true;
        }
        if (!Yii::$app->request->isAjax){
            if ($this->configs->userControl || $this->configs->guestControl){
                UControl::guestsAndUsersControl($this->configs->guestControl, $this->configs->userControl);
            }
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @return null
     */
    public function getConfigs()
    {
        if ($this->_configs === null) {
            $this->_configs = Yii::$app->configs;
        }
        return $this->_configs;
    }
}