<?php

namespace app\modules\adminxx\controllers;

use app\components\AccessHelper;
use app\components\conservation\ActiveDataProviderConserve;
use app\modules\admin\models\User;
use app\modules\adminxx\models\UControl;
use app\modules\orgstat\models\StaffOrderFilter;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;


class MainController extends Controller
{
    public $layout = '@app/modules/adminxx/views/layouts/adminxxLayout.php';

    /**
     * Ответ, который будет возвращаться на AJAX-запросы
     * @var array
     */
    public $result = [
        'status' => false,
        'data' => 'Інформацію не знайдено'
    ];

    public function beforeAction($action)
    {
        if (defined('YII_DEBUG') && YII_DEBUG) {
            \Yii::$app->getAssetManager()->forceCopy = true;
        }
        if (!\Yii::$app->request->isAjax){
            if (\Yii::$app->configs->userControl || \Yii::$app->configs->guestControl){
                $ret = UControl::guestsAndUsersControl();
            }
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}